### ISSUE TITLE
可视化结果

### ISSUE THREAD

**Issue by tianjizhizhou** [aixiaobaikkk/LUCF-Net-main#2]
您好，可以提供一下可视化结果吗，我的邮箱1950793880@qq.com

**Comment by aixiaobaikkk** [comment]
参考我的论文



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月04日 12:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [aixiaobaikkk/LUCF-Net-main] 可视化结果 (Issue #2) |

***@***.***

**Comment by tianjizhizhou** [comment]
> 参考我的论文
> […](#)
> ---- 回复的原邮件 ---- |发件人 |***@***.***> | |日期 |2024年08月04日 12:23 | |收件人 |***@***.***> | |抄送至 |***@***.***> | |主题 |[aixiaobaikkk/LUCF-Net-main] 可视化结果 （Issue #2） | ***@***.*** — 直接回复此邮件，在GitHub上查看，或取消订阅。 您收到此消息是因为您订阅了此线程。邮件ID： ***@***.***>
是否可以加个联系方式交流一下，我的qq:1950793880

**Comment by tianjizhizhou** [comment]
你好，我有些问题想和你交流，可以加我QQ吗？非常感谢🙏🏻，祝您科研顺利。我的QQ号:1950793880
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年08月04日 13:25 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [aixiaobaikkk/LUCF-Net-main] 可视化结果 (Issue #2) 
参考我的论文
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月04日 12:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [aixiaobaikkk/LUCF-Net-main] 可视化结果 (Issue #2) |
***@***.***

**Comment by aixiaobaikkk** [comment]
我Q1961713459



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月04日 14:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [aixiaobaikkk/LUCF-Net-main] 可视化结果 (Issue #2) |

你好，我有些问题想和你交流，可以加我QQ吗？非常感谢🙏🏻，祝您科研顺利。我的QQ号:1950793880
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年08月04日 13:25 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [aixiaobaikkk/LUCF-Net-main] 可视化结果 (Issue #2)
参考我的论文
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月04日 12:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [aixiaobaikkk/LUCF-Net-main] 可视化结果 (Issue #2) |
***@***.***
